version: "3.9"

services:
  web:
    build: .
    image: whatacommerce
    ports:
      - "3000:3000"
    volumes:
      - ./.env.local:/app/.env.local
    depends_on:
      db:
        required: true
        condition: service_healthy
    command: sh -c "npm run db && npm run start"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tfg
      POSTGRES_USER: tfg
      POSTGRES_PASSWORD: tfg
    healthcheck:
      test: pg_isready -d tfg
      interval: 10s
      timeout: 3s
      retries: 3
