version: "3"

services:
  web:
    build: .
    image: whatacommerce
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tfg
      POSTGRES_USER: tfg
      POSTGRES_PASSWORD: tfg
