name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    services:
      postgresDB:
        image: postgres
        env:
          POSTGRES_DB: tfg
          POSTGRES_USER: tfg
          POSTGRES_PASSWORD: tfg
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local file
        env:
          STRIPE_WEBHOOK_SECRET_KEY: ${{ secrets.STRIPE_WEBHOOK_SECRET_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          touch .env.local
          echo NEXTAUTH_SECRET="JustOneSecret" >> .env.local
          echo STRIPE_WEBHOOK_SECRET_KEY="$STRIPE_WEBHOOK_SECRET_KEY" >> .env.local
          echo DATABASE_URL="postgres://tfg:tfg@127.0.0.1:5432/tfg" >> .env.local
          echo NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" >> .env.local
          echo STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" >> .env.local
          echo HOST_URL="http://localhost:3000" >> .env.local
        shell: bash

      - name: Setup Database
        run: npm run db:push

      - name: Building project
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          browser: chrome
